### ISSUE TITLE
Problem with keys and Font

### ISSUE THREAD

**Issue by mswift98** [johnBuffer/Foucloids#1]
Hi. When I run the program it shows this : "Failed to load font "font.ttf" (failed to create the font face)"

And another thing is opposite to the README file, 'E' key adds a new harmonic and 'A' key removes the harmonic with highest frequency.

**Comment by johnBuffer** [comment]
Hi, 
Thank you for this issue. I did fix the text with the keys. Concerning the font you just have to put the `font.ttf` file next to the executable.

**Comment by johnBuffer** [comment]
Don't hesitate to reopen if you still have issues.
